# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooltje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leraar',
            name='foto',
            field=models.FileField(upload_to='static'),
        ),
    ]
