# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooltje', '0002_auto_20170813_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='klas',
            name='numerieke_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leraar',
            name='foto',
            field=models.ImageField(upload_to='images'),
        ),
    ]
